# .github/labeler.yml
segmenters:
  - segmenters/**/*

testing:
  - testing/**/*
  - tests/**/*

datasets:
  - datasets/**/*

metrics:
  - metrics/**/*

utils:
  - utils/**/*

documentation:
  - README.md
  - docs/**/*
  - htmlcov/**/*